###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "nomb_cliente": "Nikola Tesla",
  "telefono": 5651779,
  "ciudad": "guadalajara",
  "calle" : "lima",
  "numero" : 1152,
  "estado" : "jalisco",
  "fecha_nacimiento":"27/12/2000"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/6137e2bb2e329eb206b0073e HTTP/1.1

###
DELETE http://localhost:9000/api/users/639cec782a79ae96fdc82581 HTTP/1.1

###
PUT http://localhost:9000/api/users/639ce312b0b8125add1943c8 HTTP/1.1
Content-Type: application/json

{
  "nomb_cliente": "Nikola Tesla",
  "telefono": 5651779,
  "ciudad": "guadalajara",
  "calle" : "lima",
  "numero" : 1152,
  "estado" : "jalisco",
  "fecha_nacimiento":"27/12/2000"
}